### ISSUE TITLE
Create `useGoogleMaps` library

### ISSUE THREAD

**Issue by arantespp** [ttoss/modules#12]
### Description

This issue aims to create the hook `useGoogleMaps` and publish it to NPM. There is no specific path to do this, but we should mark some milestones before publishing. We're going to use a lib that has already published on NPM and has the MIT license. We only do this because of its license.

### Milestones

- [x] Create an NPM package inside `packages/` folder. The name of the package can be `useGoogleMaps` or simply `googleMaps`. The difference between them is that the second name is more generic, in the case we want to provide other methods than `useGoogleMaps`.
- [x] Create the package in TypeScript and check if it is buildable.
- [x] We need to discuss some tests to guarantee security and quality.
- [x] The last step is to publish to NPM.

### Question

There are some error messages inside the hook. Is it a good idea to display those errors using `@ttoss/notifications`? I mean, if we do this, we'll couple both modules, that could prevent others using `useGoogleMaps` because they don't want to use `@ttoss/notifications`. On the other hand, our lib modules are very opinionated, we're creating them to fit our needs. So, when we use `useGoogleMaps`, it'll automatically force us to use `@ttoss/notifications` and this is good because we don't need to think about it.
