### ISSUE TITLE
@ttoss/forms

### ISSUE THREAD

**Issue by arantespp** [ttoss/modules#14]
### Description

We always need a Search component. This search component is an input that receives results from API and displays them below the input, like Google.

![image](https://user-images.githubusercontent.com/16626980/123806829-b0205d00-d8c5-11eb-8f5c-eb9c4d37607b.png)

### Tasks

- [ ] Create a package called forms on the `packages/forms`.
- [ ] Implement the Search.
- [ ] Publish on `@ttoss/forms`. Such a package already exists, but don't worry, we're going to implement it in this new format.

### Search

It's not very clear to me how could we create this component, but we have some guidelines to follow. The Search component should:

- have an `onChange` props to allow make API requests with the user input;
- a `results` props that are an array that shows the API results;
- wait some time, 500 ms for instance, before calling the API.
- basic tests.

Let's discussing this issue here because there're a lot of points that we need to define before publishing.
