### ISSUE TITLE
Creating email validation

### ISSUE THREAD

**Issue by arantespp** [ttoss/modules#5]
### Description

We have our login component. We need to create a form structure to handle input validations. 

### Task

- [x] Install and get familiar with [React Hook Form 7](https://react-hook-form.com/).
- [x] Install and get familiar with [Yup](https://github.com/jquense/yup).
- [x] You can use [this reference](https://react-hook-form.com/get-started#SchemaValidation) to understand better how Yup works with React Hook Form.
- [x] Create an email validation.
- [x] Create a test that doesn't call `onSubmit` if the email is invalid and calls if is valid.

### Considerations

There are other form libraries that are also very good, as [Formik](https://formik.org/), so it's a good idea to give a look at them.
