### ISSUE TITLE
First organization

### ISSUE THREAD

**Issue by arantespp** [ttoss/modules#9]
### Description

I think it's too early to keep `modules` and `components` folder. Since this project doesn't have a defined scope, you can assure with certain which components will be classified as `modules` or `components`. My suggestion is to keep only the `components` folder and think about creating `modules` in the future if it makes sense.

#### Auth

Change the name of `Login` and `Signup` components inside `modules` to `AuthSignIn` and `AuthSignUp` inside `components` folder.

#### Form

I suggest renaming `FormControl` to `FormItem` because the latter makes more sense because it handles an input, a label, and an error message, which is an item of the form. So, instead of exporting `Form.FormControl`, we'll export `Form.Item = FormItem`.

### Tasks

- [x] Remove `modules` folder.
- [x] Change `modules/Login` to `componens/AuthSignIn`.
- [x] Change `modules/Signup` to `componens/AuthSignUp`.
- [x] Change `modules/Form` to `components/Form`.
- [x] Delete `modules/Checkout`.
- [x] Delete `/packages/components/jest.config.js`.
- [x] Delete `jest.config.base.js`.
- [x] Change `/packages/components` to `/packages/modules`.
